import Head from 'next/head'
import Link from "next/link";
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {useEffect, useState} from "react";
import {ReadWordDictionaryDto} from "../models/word-dictionary/ReadWordDictionaryDto";

const Home = () => {
    const [dictionaries, setDictionaries] = useState<ReadWordDictionaryDto[]>([]);
    
    useEffect(() => {
        fetch("https://localhost:44385/dict/")
            .then(result => result.json())
            .then(data => setDictionaries(data))
    }, []);
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {
                    dictionaries.map((item, index) => {
                        return(
                            <div>
                                <Link href={`/dict/${item.name}`} key={index}>
                                    {item.name}
                                </Link>
                            </div>
                           
                        );
                    })
                }
            </main>
            <footer>
            
            </footer>
        </div>
    )
}

export default Home;
